### PR TITLE
correct byte to int

### PR DESCRIPTION
**Pull request by harisyuana**
the original code has a bug, analog return int.

### CODE REVIEW

**Comment by harisyuana** [comment]
pull request submitted.
what this comment for?
I need to try it. :dancer:

**Comment by ToniCorinne** [comment]
Glad to see the tutorial worked! Let us know if you have any questions regarding this, otherwise I'm going to leave the repo as-is for other customers to use with the tutorial.

**Comment by harisyuana** [comment]
Sparkfun article about github really help me to get in touch with this repository. Is there any tutorial about "branch"  in sparkfun? I often see it but don't know why and how to use it.
   
Is it you, Toni Klopfenstein, in http://www.oshwa.org/2014/10/17/conversations-with-two-summit-scholarship-recipients/ ? It inspire me.

Sorry too much comment here. I think it will be 2nd facebook for coders and hobbies :D

**Comment by ToniCorinne** [comment]
The branches are generally for internal use. There's no way to hide those as private while keeping the repository open. Keep that in mind if you ever see a branch - that's a work in progress and the files cannot be guaranteed to be valid or functioning.

Yes, that's me! I'm very lucky to get to work with such awesome people, both here at SparkFun and on OSHWA. 

We're here to answer questions, so ask away :)

**Pull request closed without merging**
